spring:
    zipkin:
        base-url: http://localhost:9411/

server:
    port: 8770
    
zuul:
  #ignoredServices: '*'
  routes:
    greetingsclient:
      path: /greetingclient/**
      serviceId: GREETING-CLIENT-SERVICE
      stripPrefix: false
    greetings:
      path: /greeting/**
      serviceId: GREETING-SERVICE
      stripPrefix: false
      
endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false
    
eureka:
    client:
        serviceUrl:
             defaultZone: http://localhost:8761/eureka/
